### ISSUE TITLE
Not working with Windows3.2 and OPL2LPT

### ISSUE THREAD

**Issue by zhblue** [andreiw/adlib21#1]
compiled with DDK 3.1 and VC++1.52
non-debug version 26kb , replace msadlib.drv ,not working
media player complain about without [MCI] Midi device or haredware missing , installed & removed about 10 times.
no miracle, really hope to get it work.

**Comment by andreiw** [comment]
Check these prebuilts out - https://github.com/andreiw/adlib21/tree/master/bin

If these don't work, tell me your LPT1 port.

**Comment by andreiw** [comment]
Ok,  new prebuilts at https://github.com/andreiw/adlib21/tree/master/PUB

Importantly, these fix a bug that would prevent the OPL2LPT/OPLT3LPT build from working unless the vadlibd.386 driver was commented out from systemi.init.

You should be good now.
